# Generated by Django 4.1 on 2022-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagepostdetails",
            name="image",
            field=models.ImageField(default="default.jpeg", upload_to="home_page"),
        ),
    ]
